/**
 * usePWA.js
 * =========
 * React hook that:
 *  • Registers the Workbox service worker (vite-plugin-pwa)
 *  • Tracks online/offline connectivity
 *  • Exposes update-available state and a skipWaiting trigger
 *  • Persists last-known risk data to IndexedDB so the app stays useful
 *    for emergency responders with no connectivity
 */

import { useEffect, useState, useCallback } from 'react';

// IndexedDB helper — stores the last successful API responses offline
const DB_NAME    = 'cyclonesense-offline';
const DB_VERSION = 1;
const STORE_NAME = 'snapshots';

function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = e => {
      const db = e.target.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'key' });
      }
    };
    req.onsuccess = e => resolve(e.target.result);
    req.onerror   = e => reject(e.target.error);
  });
}

export async function saveOfflineSnapshot(key, data) {
  try {
    const db = await openDB();
    const tx = db.transaction(STORE_NAME, 'readwrite');
    tx.objectStore(STORE_NAME).put({ key, data, savedAt: Date.now() });
    return new Promise((res, rej) => { tx.oncomplete = res; tx.onerror = rej; });
  } catch (e) {
    console.warn('[PWA] IndexedDB save failed:', e);
  }
}

export async function loadOfflineSnapshot(key) {
  try {
    const db = await openDB();
    return new Promise((resolve, reject) => {
      const req = db.transaction(STORE_NAME, 'readonly')
                    .objectStore(STORE_NAME).get(key);
      req.onsuccess = e => resolve(e.target.result?.data ?? null);
      req.onerror   = e => reject(e.target.error);
    });
  } catch (e) {
    console.warn('[PWA] IndexedDB load failed:', e);
    return null;
  }
}

// ─── Hook ────────────────────────────────────────────────────────────────────

export function usePWA() {
  const [isOnline,         setIsOnline]         = useState(navigator.onLine);
  const [updateAvailable,  setUpdateAvailable]  = useState(false);
  const [swRegistration,   setSwRegistration]   = useState(null);
  const [offlineDataAge,   setOfflineDataAge]   = useState(null);

  // Track network status
  useEffect(() => {
    const up   = () => setIsOnline(true);
    const down = () => setIsOnline(false);
    window.addEventListener('online',  up);
    window.addEventListener('offline', down);
    return () => { window.removeEventListener('online', up); window.removeEventListener('offline', down); };
  }, []);

  // Register Workbox SW (generated by vite-plugin-pwa)
  useEffect(() => {
    if (!('serviceWorker' in navigator)) return;

    // vite-plugin-pwa generates /sw.js in dist; in dev mode it's virtual
    const swPath = import.meta.env.DEV ? '/dev-sw.js?dev-sw' : '/sw.js';

    navigator.serviceWorker.register(swPath, { scope: '/', type: import.meta.env.DEV ? 'module' : 'classic' })
      .then(reg => {
        setSwRegistration(reg);
        console.log('[PWA] Service worker registered:', reg.scope);

        // Listen for a waiting SW (new version downloaded)
        const checkWaiting = () => {
          if (reg.waiting) setUpdateAvailable(true);
        };
        reg.addEventListener('updatefound', () => {
          const newSW = reg.installing;
          newSW?.addEventListener('statechange', () => {
            if (newSW.state === 'installed' && navigator.serviceWorker.controller) {
              setUpdateAvailable(true);
            }
          });
        });
        checkWaiting();
      })
      .catch(err => console.warn('[PWA] SW registration failed:', err));
  }, []);

  // Apply the waiting SW update
  const applyUpdate = useCallback(() => {
    if (swRegistration?.waiting) {
      swRegistration.waiting.postMessage({ type: 'SKIP_WAITING' });
      window.location.reload();
    }
  }, [swRegistration]);

  // Check age of offline snapshot on mount
  useEffect(() => {
    openDB().then(db => {
      const req = db.transaction(STORE_NAME, 'readonly')
                    .objectStore(STORE_NAME).get('analysisData');
      req.onsuccess = e => {
        const record = e.target.result;
        if (record) {
          const ageMin = Math.round((Date.now() - record.savedAt) / 60_000);
          setOfflineDataAge(ageMin);
        }
      };
    }).catch(() => {});
  }, []);

  return { isOnline, updateAvailable, applyUpdate, offlineDataAge };
}
